[package]
name = "snake"
version = "0.1.0"
authors = ["Christian Hultin <christian.h.hultin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = "0.2.2"
ggez = "0.5.1"
oorandom = "11.1.3"
